const students = window.initialStudents || [
  { initials: 'AK', name: 'Aicha Kouassi', className: '3e A', cycle: 'Secondaire', phone: '07 08 22 14 90', status: 'Inscrite', statusClass: 'good' },
  { initials: 'KM', name: 'Koffi Marc', className: 'Terminale C', cycle: 'Secondaire', phone: '05 44 19 87 21', status: 'Inscrit', statusClass: 'good' },
  { initials: 'YS', name: 'Yao Sarah', className: '6e B', cycle: 'Secondaire', phone: '01 72 63 48 05', status: 'A verifier', statusClass: 'pending' },
  { initials: 'DO', name: 'Diomande Oumar', className: 'CM2 A', cycle: 'Primaire', phone: '07 09 55 31 64', status: 'Inscrit', statusClass: 'good' },
  { initials: 'KB', name: 'Konan Bintou', className: '4e C', cycle: 'Secondaire', phone: '05 66 42 18 73', status: 'Retard paiement', statusClass: 'late' }
];
const schoolData = window.initialData || { classes: [], entityCounts: {} };
const viewNames = { dashboard: 'Tableau de bord', students: 'Eleves', attendance: 'Presences', grades: 'Notes & bulletins', finance: 'Finances', classes: 'Classes', documents: 'Documents' };
const appView = document.querySelector('#appView');
const breadcrumbCurrent = document.querySelector('#breadcrumbCurrent');
const toast = document.querySelector('#toast');
const modalBackdrop = document.querySelector('#modalBackdrop');
let currentView = 'dashboard';

function pageHeader(eyebrow, title, subtitle, button = '') {
  return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div>${button}</div>`;
}
function stat(label, value, change, icon, warn = false) { return `<article class="stat-card"><span class="stat-icon">${icon}</span><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-change ${warn ? 'warn' : ''}">${change}</div></article>`; }
function dashboard() {
  return `${pageHeader('Mercredi 19 Aout 2026', 'Bonjour Adama,', 'Voici ce qui se passe dans votre etablissement aujourd’hui.', '<button class="primary-button" data-action="add-student">+ Nouvelle inscription</button>')}
    <div class="stats-grid">${stat('Eleves inscrits', schoolData.entityCounts.students || students.length, 'Dossiers dans SQLite', '◉')}${stat('Classes actives', schoolData.entityCounts.classes || schoolData.classes.length, 'Primaire et secondaire', '▦')}${stat('Evaluations', schoolData.entityCounts.evaluations || 0, 'Enregistrees cette annee', '▤')}${stat('Dossiers a verifier', students.filter(student => student.status === 'A verifier').length, 'Necessitent votre attention', '!', true)}</div>
    <div class="dashboard-grid"><article class="panel"><div class="panel-title"><h2>Evolution des effectifs</h2><button class="quiet-link" data-action="show-toast">Cette annee ⌄</button></div><div class="chart">${[['Sep',58],['Oct',67],['Nov',64],['Dec',72],['Jan',79],['Fev',83],['Mar',87],['Avr',90],['Mai',94],['Juin',97]].map(x => `<div class="bar-wrap"><div class="bar" style="height:${x[1]}%"></div><span class="bar-label">${x[0]}</span></div>`).join('')}</div><div class="legend"><span>Effectif total</span><span>Objectif annuel</span></div></article><article class="panel"><div class="panel-title"><h2>Programme du jour</h2><button class="quiet-link" data-view-link="classes">Voir tout</button></div><div class="schedule"><div class="schedule-row"><span class="schedule-time">08:00 - 10:00</span><div class="schedule-class"><strong>Mathematiques · 3e A</strong><span>M. Kouame · Salle 12</span></div></div><div class="schedule-row"><span class="schedule-time">10:15 - 12:00</span><div class="schedule-class"><strong>Francais · 4e C</strong><span>Mme N'Guessan · Salle 8</span></div></div><div class="schedule-row"><span class="schedule-time">14:00 - 16:00</span><div class="schedule-class"><strong>Sciences · Terminale C</strong><span>M. Bamba · Laboratoire</span></div></div><div class="schedule-row"><span class="schedule-time">16:15 - 17:00</span><div class="schedule-class"><strong>Etude dirigee · 6e B</strong><span>Mme Yao · Salle 5</span></div></div></div></article></div>
    <div class="bottom-grid"><article class="table-panel"><div class="panel-title"><h2>Dernieres inscriptions</h2><button class="quiet-link" data-view-link="students">Voir les eleves</button></div>${studentTable(students.slice(0, 4))}</article><article class="panel"><div class="panel-title"><h2>Repartition des classes</h2><button class="quiet-link" data-view-link="classes">Details</button></div><div class="mini-grid"><div class="mini-card"><span>Primaire</span><strong>328</strong><span>12 classes</span></div><div class="mini-card"><span>College</span><strong>356</strong><span>14 classes</span></div><div class="mini-card"><span>Lycee</span><strong>158</strong><span>7 classes</span></div></div></article></div>`;
}
function studentTable(rows) { return `<table class="data-table"><thead><tr><th>Eleve</th><th>Cycle</th><th>Classe</th><th>Contact</th><th>Statut</th></tr></thead><tbody>${rows.map(s => `<tr><td><div class="student-cell"><span class="student-avatar">${s.initials}</span><strong>${s.name}</strong></div></td><td><span class="status ${s.cycle === 'Primaire' ? 'good' : 'pending'}">${s.cycle || 'Secondaire'}</span></td><td>${s.className}</td><td>${s.phone}</td><td><span class="status ${s.statusClass}">${s.status}</span></td></tr>`).join('')}</tbody></table>`; }
function studentsView() { return `${pageHeader('Scolarite', 'Eleves', `${schoolData.entityCounts.students || students.length} dossiers actifs pour l’annee scolaire 2025 - 2026.`, '<button class="primary-button" data-action="add-student">+ Nouvelle inscription</button>')}<div class="table-panel full-panel"><div class="view-toolbar"><label class="search-box"><span>⌕</span><input id="studentSearch" placeholder="Rechercher un eleve, matricule..." type="search"></label><select class="filter-select" id="classFilter"><option value="">Primaire et secondaire</option><option value="Primaire">Primaire</option><option value="Secondaire">Secondaire</option></select><button class="quiet-link" data-action="show-toast">Exporter ↓</button></div><div id="studentTable">${studentTable(students)}</div></div>`; }
function classesView() { const rows = schoolData.classes || []; return `${pageHeader('Organisation', 'Classes & emploi du temps', 'Classes réelles de l’annee scolaire 2025 - 2026.', '<button class="primary-button" data-action="show-toast">+ Creer une classe</button>')}<div class="stats-grid">${stat('Classes actives', rows.length, 'Primaire et secondaire', '▦')}${stat('Eleves affectes', rows.reduce((total, item) => total + Number(item.student_count), 0), 'Inscriptions validees', '◉')}${stat('Primaire', rows.filter(item => item.cycle === 'Primaire').length, 'Classes du cycle', '⌂')}${stat('Secondaire', rows.filter(item => item.cycle === 'Secondaire').length, 'College et lycee', '▤')}</div><div class="table-panel full-panel"><div class="panel-title"><h2>Repartition des classes</h2><button class="quiet-link" data-action="show-toast">Exporter ↓</button></div><table class="data-table"><thead><tr><th>Classe</th><th>Cycle</th><th>Niveau</th><th>Effectif</th><th>Capacite</th><th>Occupation</th></tr></thead><tbody>${rows.map(item => { const occupancy = item.capacity ? Math.round(Number(item.student_count) / Number(item.capacity) * 100) : 0; return `<tr><td><strong>${item.name}</strong></td><td><span class="status ${item.cycle === 'Primaire' ? 'good' : 'pending'}">${item.cycle}</span></td><td>${item.level_name}</td><td>${item.student_count}</td><td>${item.capacity}</td><td><span class="status ${occupancy > 90 ? 'late' : 'good'}">${occupancy}%</span></td></tr>`; }).join('')}</tbody></table></div>`; }
function genericView(view) { if (view === 'classes') return classesView(); const data = { attendance: ['Vie scolaire', 'Presences', 'Suivi des presences et retards du mercredi 19 aout 2026.', '94,8%', '27 absences', '14 retards'], grades: ['Pedagogie', 'Notes & bulletins', 'Suivi des evaluations et publications en attente.', '76%', '12 bulletins a valider', '4 evaluations ouvertes'], finance: ['Comptabilite', 'Finances', 'Suivi des frais scolaires et des encaissements.', '8,45 M', '1,18 M restant', '94% des echeances reglees'], documents: ['Administration', 'Documents', 'Modeles et documents generes par l’etablissement.', '128', 'documents ce mois', '6 modeles actifs'] }[view]; return `${pageHeader(data[0], data[1], data[2], '<button class="primary-button" data-action="show-toast">+ Creer</button>')}<div class="stats-grid">${stat('Indicateur principal', data[3], data[4], '◈')}${stat('A traiter', data[5], 'Mis a jour aujourd’hui', '!', true)}${stat('Annee active', '2025 - 2026', 'Cote d’Ivoire · Abidjan', '⌖')}${stat('Derniere synchronisation', '08:42', 'Toutes les donnees sont a jour', '↻')}</div><div class="table-panel full-panel"><div class="panel-title"><h2>Activite recente</h2><button class="quiet-link" data-action="show-toast">Exporter ↓</button></div><div class="empty-note">Les données de ce module sont prêtes dans SQLite.<br><button class="quiet-link" data-action="show-toast">Configurer le module →</button></div></div>`; }
function render(view = currentView) { currentView = view; breadcrumbCurrent.textContent = viewNames[view]; appView.innerHTML = view === 'dashboard' ? dashboard() : view === 'students' ? studentsView() : genericView(view); document.querySelectorAll('.nav-item').forEach(btn => btn.classList.toggle('active', btn.dataset.view === view)); bindActions(); }
function showToast(message = 'Action enregistree') { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function openStudentModal() { modalBackdrop.hidden = false; document.querySelector('#modalContent').innerHTML = `<h2 id="modalTitle">Nouvelle inscription</h2><p>Creer le dossier d’un nouvel eleve pour l’annee 2025 - 2026.</p><form class="form-grid" id="studentForm"><div class="form-field"><label for="firstName">Prenoms</label><input id="firstName" required placeholder="Ex. Aicha"></div><div class="form-field"><label for="lastName">Nom</label><input id="lastName" required placeholder="Ex. Kouassi"></div><div class="form-field"><label for="className">Classe</label><select id="className"><option>CP1 A</option><option>CM2 A</option><option>6e B</option><option>3e A</option><option>Terminale C</option></select></div><div class="form-field"><label for="phone">Telephone responsable</label><input id="phone" placeholder="07 00 00 00 00"></div><button class="primary-button form-submit" type="submit">Enregistrer l’inscription</button></form>`; document.querySelector('#studentForm').addEventListener('submit', async e => { e.preventDefault(); const form = e.currentTarget; const response = await fetch('api.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ firstName: form.firstName.value, lastName: form.lastName.value, className: form.className.value, phone: form.phone.value }) }); const result = await response.json(); if (!response.ok) { showToast(result.message || 'Impossible d’enregistrer le dossier'); return; } students.unshift(result.student); closeModal(); render('students'); showToast(result.message); }); }
function closeModal() { modalBackdrop.hidden = true; }
function bindActions() { document.querySelectorAll('[data-view-link]').forEach(x => x.addEventListener('click', () => render(x.dataset.viewLink))); document.querySelectorAll('[data-action="add-student"]').forEach(x => x.addEventListener('click', openStudentModal)); document.querySelectorAll('[data-action="show-toast"]').forEach(x => x.addEventListener('click', () => showToast('Fonction disponible dans la prochaine etape'))); const search = document.querySelector('#studentSearch'); const classFilter = document.querySelector('#classFilter'); const updateStudentTable = () => { const value = (search?.value || '').toLowerCase(); const cycle = classFilter?.value || ''; const filtered = students.filter(s => `${s.name} ${s.className} ${s.phone}`.toLowerCase().includes(value) && (!cycle || s.cycle === cycle)); document.querySelector('#studentTable').innerHTML = filtered.length ? studentTable(filtered) : '<div class="empty-note">Aucun eleve ne correspond a votre recherche.</div>'; }; if (search) search.addEventListener('input', updateStudentTable); if (classFilter) classFilter.addEventListener('change', updateStudentTable); }
document.querySelectorAll('.nav-item').forEach(btn => btn.addEventListener('click', () => { render(btn.dataset.view); document.querySelector('.sidebar').classList.remove('open'); })); document.querySelector('#modalClose').addEventListener('click', closeModal); modalBackdrop.addEventListener('click', e => { if (e.target === modalBackdrop) closeModal(); }); document.querySelector('#notificationButton').addEventListener('click', () => showToast('3 notifications a consulter')); document.querySelector('#yearButton').addEventListener('click', () => showToast('Annee active : 2025 - 2026')); document.querySelector('#mobileMenu').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open')); render();
